# Generated by Django 5.2.4 on 2025-07-26 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_source',
            field=models.CharField(choices=[('External', 'External'), ('Internal', 'Internal'), ('CM', 'Contract Manufacturer')], default='External', help_text='Source of the batch', max_length=50),
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(choices=[('Production', 'Production'), ('R&D', 'R&D'), ('Sample', 'Sample'), ('Return', 'Return')], default='Production', help_text='Type of batch', max_length=50),
        ),
        migrations.AddField(
            model_name='itemrecord',
            name='segregation_rule_required',
            field=models.BooleanField(default=False, help_text='Whether segregation rules are required'),
        ),
        migrations.AddField(
            model_name='itemrecord',
            name='spec_verified',
            field=models.BooleanField(default=False, help_text='Whether specification has been verified'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='preferred_vendor',
            field=models.BooleanField(default=False, help_text='Preferred vendor flag'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='spec_verified',
            field=models.BooleanField(default=False, help_text='Whether specification has been verified'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='storage_location',
            field=models.ForeignKey(blank=True, help_text='Where the batch is currently stored', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storagelocation'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='dispatch_method',
            field=models.CharField(blank=True, choices=[('Courier', 'Courier'), ('Hand Delivery', 'Hand Delivery'), ('Postal', 'Postal'), ('Express', 'Express'), ('Refrigerated', 'Refrigerated'), ('Frozen', 'Frozen'), ('Controlled Temperature', 'Controlled Temperature'), ('Hazardous Material', 'Hazardous Material'), ('Air Freight', 'Air Freight'), ('Sea Freight', 'Sea Freight'), ('Road Freight', 'Road Freight')], help_text='Mode of dispatch', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='disposed_as',
            field=models.CharField(blank=True, choices=[('Neutralized', 'Neutralized'), ('Incinerated', 'Incinerated'), ('Returned', 'Returned'), ('Landfill', 'Landfill'), ('Recycled', 'Recycled'), ('Composted', 'Composted'), ('Autoclaved', 'Autoclaved'), ('Chemical Treatment', 'Chemical Treatment'), ('Biological Treatment', 'Biological Treatment'), ('Thermal Treatment', 'Thermal Treatment')], help_text='Disposal method used', max_length=50),
        ),
    ]
