# Generated by Django 5.2.4 on 2025-07-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_batch_supplier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='next_review_due',
            field=models.DateField(blank=True, help_text='When next QA check is expected', null=True),
        ),
        migrations.AlterField(
            model_name='itemrecord',
            name='chemical_family',
            field=models.CharField(blank=True, choices=[('Peroxides', 'Peroxides'), ('Nitrates', 'Nitrates'), ('Chlorates', 'Chlorates'), ('Alcohols', 'Alcohols'), ('Ketones', 'Ketones'), ('Hydrocarbons', 'Hydrocarbons'), ('Hydrochloric Acid (HCl)', 'Hydrochloric Acid (HCl)'), ('Nitric Acid (HNO₃)', 'Nitric Acid (HNO₃)'), ('Citric Acid', 'Citric Acid'), ('Sodium Hydroxide (NaOH)', 'Sodium Hydroxide (NaOH)'), ('Potassium Hydroxide (KOH)', 'Potassium Hydroxide (KOH)'), ('Ammonia', 'Ammonia'), ('Diethyl Ether', 'Diethyl Ether'), ('Tetrahydrofuran (THF)', 'Tetrahydrofuran (THF)'), ('Cyanides', 'Cyanides'), ('Aflatoxins', 'Aflatoxins'), ('Arsenic Compounds', 'Arsenic Compounds'), ('Bacteria', 'Bacteria'), ('Viruses', 'Viruses'), ('Bloodborne Pathogens', 'Bloodborne Pathogens')], help_text='Subgroup within hazard category', max_length=100),
        ),
    ]
