# Generated by Django 5.2.4 on 2025-07-26 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_batch_batch_source_batch_batch_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='supplier_code',
            field=models.ForeignKey(blank=True, help_text='Source supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
    ]
